---

- name: Clean up a project
  hosts: localhost
  vars:
    deployment: "{{ lookup('env', 'DEPLOYMENT') }}"
  tasks:
    - name: include variables
      include_vars: ../vars/{{ deployment }}.yml

    - name: oc login
      command: oc login {{ host }} --token={{ api_key }} --insecure-skip-tls-verify
      # it doesn't change anything, so don't report 'changed'
      changed_when: false

    - name: oc project
      command: oc project {{ project }}
      # it doesn't change anything, so don't report 'changed'
      changed_when: false

    - name: oc delete all
      command: oc delete all,cm,secrets,pvc --all
